export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const HANDLE_SIGN_IN_SUCCESS = 'HANDLE_SIGN_IN_SUCCESS';
export const HANDLE_SIGN_IN_FAILURE = 'HANDLE_SIGN_IN_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';
